[workspace]
members = [
    "const-calculation-scripts/scripts",
    "libcerf",
    "sts-lib",
    "sts-cbindings",
    "sts-pybindings",
    "sts-cmd",
]
default-members = [
    "libcerf",
    "sts-lib",
    "sts-cbindings",
]
resolver = "2"
